### ISSUE TITLE
Is there codes for the diffusion decoder as well?

### ISSUE THREAD

**Issue by XavierXiao** [drboog/Shifted_Diffusion#1]
Current codes are for the diffusion prior, and it seems like it is combined with Stable Diffusion. Is there codes for the cascades diffusion decoder in your paper?

**Comment by drboog** [comment]
Hi, we are not able to release the code and checkpoint for that diffusion decoder because of company policy. 
That's why I re-write the code so that it can be combined with Stable Diffusion 2.
For the cascade diffusion decoder, our implementation is similar to https://github.com/lucidrains/DALLE2-pytorch, but with some internal dependencies.
